### PR TITLE
Add optional replacement value for truncated values

### PR DESCRIPTION
**Pull request by lwhiteley**

### CODE REVIEW

**Comment by mrsteele** [comment]
Hey, just wanted to let you know something funky happened with travis so I had to close and reopen to rerun CI.

**Comment by lwhiteley** [comment]
no problem, was wondering why it was taking a year to build 👍

**Comment by mrsteele** [comment]
This looks good with an exception to the linting.

Run `npm run standard` locally to test your code with our linter. We use [http://standardjs.com/rules.html](standardjs) as our linter.

Once it passes the tests I can merge.

**Comment by mrsteele** [comment]
Looks like `v1.2.0` is ready for use! Thanks for the PR!

**Comment by lwhiteley** [comment]
no probs, thanks for the initial work in this cool library

**Pull request merged**
