### PR TITLE
Tooling updates

### LINKED ISSUE #64: babel-register causing build issues
We've been using this lib on the web, and realised that when the [index.js](https://github.com/mrsteele/json-truncate/blob/master/index.js) goes through webpack, it builds in babel-register.

we haven't noticed this until it also started failing the build due to a mismatch in core-js, which is a dependency of babel-register.

I guess my question is what your reasons are for publishing the library this way, when you already have the built dist/ in there?

### PR DESCRIPTION
**Pull request by ZeeCoder**
Fixes #64

### CODE REVIEW

**Comment by mrsteele** [comment]
I still think docs would need to be a thing. Any reason we can’t keep that using jsdoc?

**Comment by ZeeCoder** [comment]
I think I removed it because it didn't work, but I'll double check.

**Comment by ZeeCoder** [comment]
image
@mrsteele yeah it doesn't work in master, so I removed it assuming it wasn't needed.

**Comment by ZeeCoder** [comment]
Anything else I can do for you @mrsteele ?

**Comment by mrsteele** [comment]
Sorry, it was holiday here so I was away from my email.

Can you add jsdoc https://www.npmjs.com/package/jsdoc

It should use the same syntax, but not support the newer ES stuff (which we dropped anyways).

Just don't wanna lose support of something we had before.

**Comment by ZeeCoder** [comment]
@mrsteele done 👌

**Comment by ZeeCoder** [comment]
@mrsteele when could I expect a release :pray: ? Not familiar with how this semantic versioning works.

**Comment by mrsteele** [comment]
Ah, it was supposed to include a `feat:` or `fix:` prefix in the commit. I'll manually push a release now.

**Comment by ZeeCoder** [comment]
I see, sorry I didn't realise.
Thanks man! :+1:

**Pull request merged**
